// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs0a_prLlDs6nRv7y75fqB0BB4rQ_104Q',
    appId: '1:1008149841824:web:028ec1333b35039284c6c5',
    messagingSenderId: '1008149841824',
    projectId: 'productivityapp-c3b55',
    authDomain: 'productivityapp-c3b55.firebaseapp.com',
    storageBucket: 'productivityapp-c3b55.firebasestorage.app',
    measurementId: 'G-LWS347L231',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgeA3eymg07-OkbJyaIrd6_dRYJshwRIA',
    appId: '1:1008149841824:android:8c6264742242f6f884c6c5',
    messagingSenderId: '1008149841824',
    projectId: 'productivityapp-c3b55',
    storageBucket: 'productivityapp-c3b55.firebasestorage.app',
  );
}
